// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeService() (*Service, error) {
	message := NewMessage()
	greeter := NewGreeter(message)
	service := NewService(greeter)
	return service, nil
}
